# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20181222_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(choices=[('pm', 'permission'), ('df', 'default')], default='df', max_length=200),
        ),
    ]
